# West manifest for Memfault Example Application

manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      # fixed commit off main
      revision: 7fc6ef28d3dacad1c1c67791fc645031529d3c64

      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - cmsis
          - hal_nxp
          - mbedtls
          - picolibc
          - segger # unfortunately required, the NXP boards y-select HAS_SEGGER_RTT

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      revision: "1.7.6"

    - name: wolfssl
      path: modules/crypto/wolfssl
      url: https://github.com/wolfssl/wolfssl
      revision: v5.7.0-stable
