# West manifest for Memfault Example Application

manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main

      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - cmsis
          - hal_nxp
          - mbedtls
          - mcuboot
          - picolibc
          - segger # unfortunately required, the NXP boards y-select HAS_SEGGER_RTT

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      revision: "1.7.6+zephyr-hwinfo"
