# West manifest for Memfault Example Application

manifest:
  projects:
    - name: zephyr
      # MCX-N support was added here upstream:
      # https://github.com/zephyrproject-rtos/zephyr/commit/e4e463af812e61bb5bfb4b1087d48e1dbcd9d8d5
      # And board support was added here:
      # https://github.com/zephyrproject-rtos/zephyr/commit/8fa1c6d9c6cbc7972f482b17584c48b4ea952e55
      # Use a commit that's a little later, that seems more stable.
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 369e40b27bca1f08fefe23924f7dc82dd096c53f

      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - cmsis
          - hal_nxp
          - mbedtls
          - picolibc
          - segger # unfortunately required, the NXP boards y-select HAS_SEGGER_RTT

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      revision: "1.7.2"
