# West manifest for Memfault Example Application

manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.5.0
      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
            - cmsis
            - picolibc
            - hal_nxp
            - mbedtls

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      # Note: normally this would be pinned to a specific SDK tag instead of
      # master
      revision: master
